question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The set of all algebraic numbers is countable.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "According to Norse mythology, Loki is a mother.", "answer": "True"},
    {"text": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.", "answer": "True"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "The sum of any two odd integers is odd.", "answer": "False"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to "
             "eat.", "answer": "True"},
    {"text": "Skateboarding was included in the 2020 Summer Olympics in Tokyo.", "answer": "True"},
    {"text": "A wyvern is the same as a dragon.", "answer": "False"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "An equilateral triangle always has every angle measuring 60 degrees.;.", "answer": "True"},
    {"text": "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "There are a total of 20 races in Formula One 2016 season.", "answer": "False"},
    {"text": "A scalene triangle has two sides of equal length.", "answer": "False"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "A universal set, or a set that contains all sets, exists.", "answer": "False"},
    {"text": "Roger Federer is a famous soccer player.", "answer": "False"}
]
